### ISSUE TITLE
ModuleNotFoundError: No module named 'crfnet'

### ISSUE THREAD

**Issue by AotianDong** [nacayu/CRFNet_ReproduceOn_Tensorflow2.4.1#1]
I have installed all of the packages needed, but when I run "python test_crfnet.py --model saved_models/crf_net.h5 --config configs/crf_net.cfg --st 0.5" in the bash, it raised an error "ModuleNotFoundError: No module found named crfnet". Here are the details that the shell displayed:
```bash
Using TensorFlow backend.
2022-04-24 20:13:05.213696: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
Traceback (most recent call last):
  File "~/Documents/code/CRFNet_ReproduceOn_Tensorflow2.4.1/test_crfnet.py", line 42, in <module>
    import crfnet  # noqa: F401
ModuleNotFoundError: No module named 'crfnet'

Process finished with exit code  1
```
@nacayu

**Comment by nacayu** [comment]
@AotianDong sorry about that, I have forgiven to say that you should change your folder name(CRFNet_ReproduceOn_Tensorflow2.4.1)  to "crfnet".

**Comment by AotianDong** [comment]
> @AotianDong sorry about that, I have forgiven to say that you should change your folder name(CRFNet_ReproduceOn_Tensorflow2.4.1) to "crfnet".

Thanks, I solved this problem. and then there is another problem that how to change the **num_workers == 0**?
@nacayu

**Comment by AotianDong** [comment]
> @AotianDong sorry about that, I have forgiven to say that you should change your folder name(CRFNet_ReproduceOn_Tensorflow2.4.1) to "crfnet".

@nacayu 
Thanks very much, I solved this problem.
