### ISSUE TITLE
Question about starting to run your code

### ISSUE THREAD

**Issue by Kim-yhao** [nacayu/CRFNet_ReproduceOn_Tensorflow2.4.1#4]
When I try to run the train.py file, it says '**No module named 'crfnet.utils.compute_overlap**'. I notice that this file does exist, but it's not a .py file. Could you please tell me how to solve this problem? Thanks a lot!

**Comment by nacayu** [comment]
could you run other .py files or import other libs? I guess you could reinstall crfnet.

**Comment by Kim-yhao** [comment]
I reinstalled crfnet, this issues was solved. Thanks a lot.
